name: knowlumi_app
description: The KnowLumi App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  auto_route: ^7.8.4
  google_sign_in: ^6.1.5
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  injectable: ^2.3.0
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  file_picker: ^5.5.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.2
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/responses/
